from flask import Flask, render_template, request, jsonify
import re

app = Flask(__name__)

# Demo credit card numbers for testing
VALID_TEST_CARDS = {
    '4111111111111111': 'Visa',
    '5555555555554444': 'Mastercard',
    '378282246310005': 'American Express',
}

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/cart')
def cart():
    return render_template('cart.html')

@app.route('/process-payment', methods=['POST'])
def process_payment():
    data = request.json
    
    # Extract payment details
    card_number = data.get('cardNumber', '').replace(' ', '')
    expiry = data.get('expiry', '')
    cvv = data.get('cvv', '')
    amount = data.get('amount', 0)
    
    # Basic validation
    if card_number not in VALID_TEST_CARDS:
        return jsonify({
            'success': False,
            'message': 'Invalid card number'
        }), 400
    
    # Check expiry format (MM/YY)
    if not re.match(r'^(0[1-9]|1[0-2])\/([0-9]{2})$', expiry):
        return jsonify({
            'success': False,
            'message': 'Invalid expiry date'
        }), 400
    
    # Check CVV
    if not re.match(r'^[0-9]{3,4}$', cvv):
        return jsonify({
            'success': False,
            'message': 'Invalid CVV'
        }), 400
    
    # In a real application, you would integrate with a payment gateway here
    
    return jsonify({
        'success': True,
        'message': 'Payment processed successfully',
        'transaction_id': '12345',  # This would be generated by the payment gateway
        'amount': amount
    })

if __name__ == '__main__':
    app.run(debug=True)